# -*- coding: utf-8 -*-
"""Cópia de estudos operadores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yo4AmZJKN0aUeJtxjFtBQpDAglrq8tSK
"""

num1 = int(input('Digite seu primeiro numero: '))
num2 = int(input('Digite seu segundo numero: '))
operacao= input('Selecione qual operacao gostaria de realizar: ''\n' '+ para adição,''\n' '- para subtração,''\n'' * para multiplicação,''\n'' / para divisão:''\n' )
if operacao == '+':
  print('Seu resultado:', num1 + num2)

elif operacao == '-':
  print('Seu resultado:', num1 - num2)

elif operacao == '*':
  print('Seu resultado:', num1 * num2)

elif operacao == '/':
  print('Seu resultado:', num1 / num2)

else:
  print('operação invalida')

